export const track = [
    {
        uuid: 929398,
        company: {
            logo: null,
            name: "CAG REGIONAL SINGAPORE PTE. LTD.",
        },
        datePosted: "2023-03-06",
        description:
            "We are looking for a Technical Lead to lead a cross functional team serving our customer's needs.  THE ROLE    An obsessive automator who only wants to manually test things once.   A concise documenter who takes as much care of their README.md as they do their service interface.   An owner end to end, Frontend, Backend, CI/CD, Operations, understanding what it takes to build a resilient, scalable service and support it in production.   A problem solver focused on user experience.   A team leader, with prior experience mentoring junior engineers and facing off to business stakeholders.   Experienced with React and Ruby or similar frameworks   Familiar with AWS, Kubernetes and write your applications Docker first.  YOUR TASKS    Lead a team of engineers to drive monetisation initiatives within the company.   Build high quality, fault tolerant systems and products, owning all areas of implementation, frontend, backend, CI pipeline, automated test suites and operations.   Work with your product owner and business stakeholders to define the product and tech roadmaps.   Mentor the engineers within your team.   Engage with the wider engineering organization, making sure your tech roadmap aligns with the other teams ",
        dueDate: "2023-04-05",
        jobTitle: "Tech Lead",
        jobType: ["FULL_TIME", "FULL_TIME"],
        location: {
            address: "EON SHENTON, 70 SHENTON WAY",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 14000,
            minValue: 12000,
            payPeriod: "MONTH",
        },
        skills: [
            "Mentoring",
            "Application Architecture",
            "Kubernetes",
            "Quality Assurance",
            "User Experience",
            "Architects",
            "Agile",
            "SQL",
            "Ruby",
            "JIRA",
            "Banking",
            "Team Leader",
            "Docker",
            "Java",
            "API",
            "Software Development",
        ],
    },
    {
        uuid: 929397,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/d1505f35fee02dabd4146b80df234925/recruit-expert.jpg",
            name: "RECRUIT EXPERT PTE. LTD.",
        },
        datePosted: "2023-03-06",
        description:
            "   Active participation in the entire software development lifecycle, focusing on solution design, coding, deployment and debugging.   Build games backend services that power Html5 and Unity games.   Brainstorm solutions and design robust, highly scalable applications that can withstand   high traffic with minimum down time together with engineers from other countries.  Requirements:    Diploma in IT or equivalent   At least 3 years of web development experience using Ruby on Rails   Proficient in Cocos or UNITY in game development  If you are keen to apply for the position, kindly email your detailed resume in MS Word to hr@recruit-expert.com Please note that only shortlisted candidates will be notified. For more job opportunities, please visit our website at www.recruit-expert.com EA Licence: 19C9701 Registration: R22111604",
        dueDate: "2023-03-13",
        jobTitle: "Tech Lead (Gaming, Ruby on Rails)",
        jobType: ["FULL_TIME"],
        location: {
            address: "THE ARCADE, 11 COLLYER QUAY",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 9000,
            minValue: 7500,
            payPeriod: "MONTH",
        },
        skills: [
            "Machine Learning",
            "Game Development",
            "Kubernetes",
            "Unit Testing",
            "JavaScript",
            "HTML5",
            "Ruby",
            "MS Word",
            "Python",
            "Ruby on Rails",
            "Debugging",
            "API",
            "Web Development",
            "Django",
            "Software Development",
        ],
    },
    {
        uuid: 929377,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/dd9ae9e912ed5aba63a94f4b77f98b75/morgan-mckinley.jpg",
            name: "MORGAN MCKINLEY PTE. LTD.",
        },
        datePosted: "2023-03-06",
        description:
            "We are partnering with one of the largest Singaporean multinational technology companies that provides users with transportation, food delivery and digital payments services via a mobile app and they have an immediate need to hire a Merchant Sales Specialist to join the team.  Job Duties:-    Oversee the entire process within merchant acquisition and onboarding.   Meet, pitch and lead negotiations with assigned/prospected merchant leads to acquire and onboard them unto food delivery merchant   Build relationships/partnerships with merchants and manage their performance and contribution to building the merchant network.   Handle day-to-day merchant queries (commercial ; operational) and ensure a smooth and efficient onboarding and post-onboarding process.   Develop and maintain a solid understanding of all products and services the merchant offers   Bring value to merchants through cross selling a wide variety of service    Responsible to achieve monthly acquisition targets   Qualifications:-    Min. 1 year of related working experience   F;B, Retail or E-commerce background is an advantage.   Excellent interpersonal and negotiation skills to build rapport and win over merchants.   Good creativity, resourcefulness, and problem-solving skills   Proficient in Microsoft Office (MS. Excel, MS. Word, and MS. Powerpoint)   Good business acumen, comfortable with numbers and analysing sales data   Interested candidates may apply through the application system or send to sg-CIcontracting@morganmckinley.com. Shortlisted candidates will be notified.  By sending us your personal data and curriculum vitae (CV), you are deemed to consent to Morgan Mckinley Pte Ltd and its affiliates to collect, use and disclose your personal data for the purposes set out in the Privacy Policy available at https://www.morganmckinley.com/sg/privacy-policy. You acknowledge that you have read, understood, and agree with the Privacy Policy.  Morgan McKinley Pte Ltd Koh Boon Sien EA Licence No: 11C5502 EA Registration No. R1110345",
        dueDate: "2023-04-05",
        jobTitle:
            "Merchant Sales Specialist - 6 Months Contract - SGD2k - Tech Giant",
        jobType: ["CONTRACTOR"],
        location: {
            address: null,
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 2000,
            minValue: 1800,
            payPeriod: "MONTH",
        },
        skills: [
            "Negotiation",
            "Sales",
            "Microsoft Office",
            "Business Acumen",
            "Administration",
            "MS Word",
            "Cross Selling",
            "Transportation",
            "Communication Skills",
            "Excel",
            "Ms Powerpoint",
            "Customer Service",
            "Able To Work Independently",
        ],
    },
    {
        uuid: 829377,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/fb0c580773376abeb9080f6022b73f72/wipro.png",
            name: "WIPRO LIMITED (SINGAPORE BRANCH)",
        },
        datePosted: "2023-03-03",
        description:
            "Job Description - Should have good knowledge in Retail Banking concepts.   - Should have in depth knowledge in Cards, Loans, Mortgages, Deposits and   Derivatives.   - Should have experience as a Data Analyst with good hands on experience in   creating statistical data models using Python/R Program.   - Should be capable of interpreting the model output and provide impactful   conclusions and suggestions to improve the business.   - Knowledge in Wholesale banking products will be an added advantage.   - Should possess basic knowledge in Teradata SQL.   - Should have good communication skills and should be able to elicit   requirement's from the Clients and document them.   -Should have In- depth knowledge in Datastage.   -Should have Good understanding of Datawarehousing concepts.   -Should have Requires exceptional expertise in development and detailed   knowledge of industry trends.    -Should have Applied the highest level technical skill and expertise in   project/team leadership to highly complex projects and problems. Job Requirements Key skills required for the job are: - Data Science (Python/R Programing) - Datastage Development  - Banking Domain-L3   As a Technical Lead with the banking domain knowledge, you are responsible for supporting project teams ; team members in terms of research and background information. You are expected to elicit and detail the client requirements via industry standard analysis techniques such as data flow modeling, case analysis, workflow analysis, functional decomposition analysis, data modeling, and object modeling. You are expected to documents the results of analysis activities using appropriate templates or tools. You are responsible across areas like requirement definition, execution and evaluation of functional tests, review, testing and analysis. You are expected to be a subject matter expert in a chosen area/function. You should have in-depth knowledge in Data Science like Python/R Programming and should be able to create data models based upon the financial data and interpret the same to provide business solutions and lead the team in development/Support.",
        dueDate: "2023-03-17",
        jobTitle: "Tech Lead (ETL)(#1986054)",
        jobType: ["FULL_TIME"],
        location: {
            address: "PLAZA 8 @ CBP, 1 CHANGI BUSINESS PARK CRESCENT",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 10000,
            minValue: 7000,
            payPeriod: "MONTH",
        },
        skills: [
            "Teradata SQL",
            "Leadership",
            "Derivatives",
            "Modeling",
            "Data Modeling",
            "Wholesale Banking",
            "Loans",
            "Workflow Analysis",
            "Interpreting",
            "Retail Banking",
            "Good Communication Skills",
            "Deposits",
            "Banking",
            "Data Science",
        ],
    },
];

export const wish = [
    {
        uuid: 1111,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/6e75040574f0e00a8948d6cd7248f3f4/rapsys-technologies.png",
            name: "RAPSYS TECHNOLOGIES PTE. LTD.",
        },
        datePosted: "2023-02-17",
        description:
            "Role: Tech Lead(Payments)  JD:    Develop modern micro-frontends, using DevOps practices to develop, test and deploy.   Develop responsive and mobile friendly designs.   Develop robust solutions with focus on security, performance, internationalization, and   browser-compatibility.   Understand the business process requirements and drive the detailed design of the   application and technical architecture components.   Configure, build and test application and technical architecture components of quality   and security.   Work with other developers, designers, and architects to make sure that the   configuration and custom components meet application requirements and performance   goals.   Plan and execute all required process steps as defined in our Agile methodologies.   Anticipate, identify, track, and resolve issues and risks affecting the delivery.   Perform L2 troubleshooting duties.  Requirements    Bachelor's Degree in Computer Science or relevant field.   At least 5 years of relevant experience in full stack development framework.   Understand and develop coherent user experience flows.   Able to collaborate in a Scrum team setting cohesively.   Perform effectively as an individual when needed.   Demonstrate clarity in communicating and presenting complex information to technical and non-technical stakeholders, both verbally and in written form.   Familiar with the following technologies:  Frontend Focus    Script: JavaScript, TypeScript, ES6, jQuery   Design ; Style: HTML5, Responsive/Adaptive Design, Design Thinking, Usability   Design, CSS3, LESS, SASS, Bootstrap   Frameworks: (At least one of the following) ReactJS + NextJS, AngularJS, VueJS   Backend: NodeJS, ExpressJS   Web DevOps ; Test: Jira, BitBucket/Git, Cypress, Jasmine, Selenium, Jest   Familiarity with AWS components such as Lambda, is a plus  Backend Focus    Frameworks: (At least one of the following) Spring Boot, Quarkus   DevOps ; Test: Git, Jenkins, SonarQube, JUnit, JMeter   Proficient in JIT 11 and up.   Familiarity with Kubernetes platform such as Openshift, is a plus ",
        dueDate: "2023-03-19",
        jobTitle: "Tech Lead(Payments)",
        jobType: ["FULL_TIME"],
        location: {
            address: "FORTUNE CENTRE, 190 MIDDLE ROAD",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 8000,
            minValue: 6500,
            payPeriod: "MONTH",
        },
        skills: [
            "Git",
            "Troubleshooting",
            "Kubernetes",
            "Scrum",
            "TypeScript",
            "User Experience",
            "Architects",
            "Agile Methodologies",
            "JavaScript",
            "HTML5",
            "JUnit",
            "JIRA",
            "Technical Architecture",
            "Usability Design",
        ],
    },
    {
        uuid: 1112,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/038b5558fa6cdb2e21e99c3cfa9b48d8/ranosys-technologies.jpg",
            name: "RANOSYS TECHNOLOGIES PTE. LTD.",
        },
        datePosted: "2023-03-01",
        description:
            " SUMMARY: The Technical Analyst plays a crucial role within a result driven, innovative Ecommerce solution. Besides owns and tracks the business requirements, the ideal candidate needs to be able to organize and execute user acceptance test, organize training and hand over the validated system feature, provide daily support to client team when they have challenge on playing with SFCC platform. Essential Duties and Responsibilities include but are not limited to the following: \u2022 Partner with key clients in the Asia Pacific region to analyze E-Commerce process and integration gaps, elicit and capture complete and unambiguous system requirements, and break down complex processes into workable units. \u2022 Listen to client\u2019s stakeholders in order to understand the high-level objectives down to the fine details and convert to accurate functional and non-functional requirements. \u2022 Own the quality and accuracy of the requirements and communicate changes and decisions to the relevant stakeholders and teammates. \u2022 Represent user, system, functional and non-functional requirements using traditional modeling artifacts that are efficient for Ranosys. \u2022 Develop test plans and test scenarios in accordance with business requirements. \u2022 Execute and document test results including functional and regression scenarios. \u2022 Lead training and User Acceptance Testing for regional teammates.  Technical Attributes of Ideal Candidate: include but are not limited to the following:   Proven track record with industry leading companies utilizing strong problem solving and analytical skills to understand business challenges and opportunities in the context of the requirements.  5 years of proven experience in business and technical requirements analysis within the Ecommerce industry, knowledge of the Sales Force Commerce Cloud platform is a plus.  Experience working within teams using waterfall and agile methodologies.  Exceptional verbal and written communication skills including the ability to communicate complex and technical concepts breakdown to appropriate level, and the courage to ask compelling and clarifying questions to ensure accuracy and understanding.  Find creative solutions to complicated and unexpected problems by leveraging teammate experience and expertise.  Proven success facilitating meetings that motivate the team, encourage participation, remain on topic, and generate expected outcomes.  Self-starter with a positive attitude and ability to work under pressure in a challenging fast paced environment with tight deadlines. Balances team and individual responsibilities and contributes to building a positive team spirit.  Excellent time management skills with ability to manage multiple tasks and assignments concurrently and deliver on commitments.  A sincere and contagious passion for building Ranosys, and a fit with Ranosys cultural values.  Fluency in English",
        dueDate: "2023-03-31",
        jobTitle: "SFCC Tech Lead",
        jobType: ["FULL_TIME"],
        location: {
            address: "OXLEY BIZHUB, 73 UBI ROAD 1",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 12000,
            minValue: 8000,
            payPeriod: "MONTH",
        },
        skills: [
            "Application Architecture",
            "Analytical Skills",
            "Modeling",
            "Team Spirit",
            "Agile Methodologies",
            "Problem Solving",
            "Requirements Analysis",
            "User Acceptance Testing",
            "Java",
            "API",
            "Software Development",
            "Business Requirements",
        ],
    },
    {
        uuid: 1113,
        company: {
            logo: "https://static.mycareersfuture.gov.sg/images/company/logos/6e75040574f0e00a8948d6cd7248f3f4/rapsys-technologies.png",
            name: "RAPSYS TECHNOLOGIES PTE. LTD.",
        },
        datePosted: "2023-02-17",
        description:
            "Role:Data Tech Lead  Job Descriptions:    Development of new data management layers and build data processes.   Solutioning and Tech Designing for Data Systems   Tech Led to drive data engineering activities   Provide support for enhancements and any BAU issues on the new data management layers and existing data lakes.   Support and migration of existing on-premises databases to AWS cloud.   Understanding the existing applications, data architecture, and suggest improvements   Lead business requirements and plan deliveries.   Handle data extractions and data analysis for the requirements.  Job Requirements:    Minimum of 10+ years of experience with Information Technology using RDBMS and Non-RDBMS and Cloud databases.   8+ years of strong hands-on experience on any of the databases like SQL/PLSQL, Oracle, MS-SQL server, Postgres, and Snowflake.   3+ years of strong experience in AWS Cloud.   Good understanding of Data integration, Data Flows, Data Quality, Data Architecture and Data Engineering.   Technical expertise in data models, data mining and segmentation techniques.   Experience in Tech Design and Solution Designing for data systems   Experience with full SDLC lifecycle and Lean or Agile development methodologies.   AWS tools and components knowledge is a plus.   CI/CD and GIT exposure   Experience on UNIX shell scripts.   Ability to work in team in diverse/multiple stakeholder environment   Ability to communicate complex technology solutions to diverse teams namely, technical, business and management teams ",
        dueDate: "2023-03-19",
        jobTitle: "Data Tech Lead",
        jobType: ["FULL_TIME"],
        location: {
            address: "FORTUNE CENTRE, 190 MIDDLE ROAD",
            country: "SG",
            locality: "Singapore",
        },
        salaryRange: {
            currency: "SGD",
            maxValue: 9000,
            minValue: 7000,
            payPeriod: "MONTH",
        },
        skills: [
            "Oracle",
            "Solutioning",
            "Segmentation",
            "Job Descriptions",
            "Unix shell",
            "Data Integration",
            "SDLC",
            "Information Technology",
            "Data Quality",
            "Data Engineering",
            "Data Mining",
            "Data Architecture",
            "GCP",
            "Databases",
            "Business Requirements",
            "Agile Development",
        ],
    },
];
